import 'package:flutter/material.dart';

class Palette {
  final String name;
  final ColorScheme light;
  final ColorScheme dark;
  final List<Color> accentColors;
  final String description;

  const Palette({
    required this.name,
    required this.light,
    required this.dark,
    required this.accentColors,
    required this.description,
  });
}

final palettes = <String, Palette>{
  'default': Palette(
    name: 'Default',
    light: ColorScheme.light(
      primary: Colors.blue,
      secondary: Colors.teal,
      surface: Colors.white,
      onSurface: Colors.black,
      primaryContainer: Colors.blue.shade100,
      secondaryContainer: Colors.teal.shade100,
      error: Colors.red,
      onError: Colors.white,
    ),
    dark: ColorScheme.dark(
      primary: Colors.blueAccent,
      secondary: Colors.tealAccent,
      surface: Colors.grey[900]!,
      onSurface: Colors.white,
      primaryContainer: Colors.blue.shade900,
      secondaryContainer: Colors.teal.shade900,
      error: Colors.redAccent,
      onError: Colors.black,
    ),
    accentColors: [
      Colors.blue,
      Colors.green,
      Colors.orange,
      Colors.purple,
      Colors.red,
      Colors.teal,
    ],
    description: 'Light and neutral tones',
  ),
  'dark': Palette(
    name: 'Dark',
    light: ColorScheme.light(
      primary: Colors.greenAccent,
      secondary: Colors.pinkAccent,
      surface: Colors.grey[100]!,
      onSurface: Colors.black,
      primaryContainer: Colors.green.shade100,
      secondaryContainer: Colors.pink.shade100,
      error: Colors.red,
      onError: Colors.white,
    ),
    dark: ColorScheme.dark(
      primary: Colors.greenAccent,
      secondary: Colors.pinkAccent,
      surface: Colors.grey[850]!,
      onSurface: Colors.white,
      primaryContainer: Colors.green.shade800,
      secondaryContainer: Colors.pink.shade800,
      error: Colors.redAccent,
      onError: Colors.black,
    ),
    accentColors: [
      Colors.greenAccent,
      Colors.pinkAccent,
      Colors.amberAccent,
      Colors.cyanAccent,
    ],
    description: 'Dark mode optimized',
  ),
  'ocean': Palette(
    name: 'Ocean',
    light: ColorScheme.light(
      primary: Colors.cyan,
      secondary: Colors.teal,
      surface: Colors.white,
      onSurface: Colors.black,
      primaryContainer: Colors.cyan.shade100,
      secondaryContainer: Colors.teal.shade100,
      error: Colors.red,
      onError: Colors.white,
    ),
    dark: ColorScheme.dark(
      primary: Colors.tealAccent,
      secondary: Colors.lightBlueAccent,
      surface: Colors.grey[900]!,
      onSurface: Colors.white,
      primaryContainer: Colors.teal.shade900,
      secondaryContainer: Colors.lightBlue.shade900,
      error: Colors.redAccent,
      onError: Colors.black,
    ),
    accentColors: [
      Colors.cyan,
      Colors.teal,
      Colors.lightBlue,
      Colors.blueAccent,
      Colors.indigoAccent,
    ],
    description: 'Blue and teal tones',
  ),
  'sunset': Palette(
    name: 'Sunset',
    light: ColorScheme.light(
      primary: Colors.orange,
      secondary: Colors.deepOrange,
      surface: Colors.white,
      onSurface: Colors.black,
      primaryContainer: Colors.orange.shade100,
      secondaryContainer: Colors.deepOrange.shade100,
      error: Colors.red,
      onError: Colors.white,
    ),
    dark: ColorScheme.dark(
      primary: Colors.deepOrangeAccent,
      secondary: Colors.pinkAccent,
      surface: Colors.grey[900]!,
      onSurface: Colors.white,
      primaryContainer: Colors.deepOrange.shade900,
      secondaryContainer: Colors.pink.shade900,
      error: Colors.redAccent,
      onError: Colors.black,
    ),
    accentColors: [
      Colors.orange,
      Colors.deepOrange,
      Colors.amber,
      Colors.pink,
      Colors.redAccent,
    ],
    description: 'Orange and pink tones',
  ),
  'forest': Palette(
    name: 'Forest',
    light: ColorScheme.light(
      primary: Colors.green,
      secondary: Colors.lightGreen,
      surface: Colors.white,
      onSurface: Colors.black,
      primaryContainer: Colors.green.shade100,
      secondaryContainer: Colors.lightGreen.shade100,
      error: Colors.red,
      onError: Colors.white,
    ),
    dark: ColorScheme.dark(
      primary: Colors.lightGreenAccent,
      secondary: Colors.greenAccent,
      surface: Colors.grey[900]!,
      onSurface: Colors.white,
      primaryContainer: Colors.green.shade900,
      secondaryContainer: Colors.lightGreen.shade900,
      error: Colors.redAccent,
      onError: Colors.black,
    ),
    accentColors: [
      Colors.green,
      Colors.lightGreen,
      Colors.lime,
      Colors.teal,
      Colors.greenAccent,
    ],
    description: 'Green tones',
  ),
  'lavender': Palette(
    name: 'Lavender',
    light: ColorScheme.light(
      primary: Colors.purple,
      secondary: Colors.purpleAccent,
      surface: Colors.white,
      onSurface: Colors.black,
      primaryContainer: Colors.purple.shade100,
      secondaryContainer: Colors.purpleAccent.shade100,
      error: Colors.red,
      onError: Colors.white,
    ),
    dark: ColorScheme.dark(
      primary: Colors.deepPurpleAccent,
      secondary: Colors.indigoAccent,
      surface: Colors.grey[900]!,
      onSurface: Colors.white,
      primaryContainer: Colors.deepPurple.shade900,
      secondaryContainer: Colors.indigo.shade900,
      error: Colors.redAccent,
      onError: Colors.black,
    ),
    accentColors: [
      Colors.purple,
      Colors.purpleAccent,
      Colors.deepPurple,
      Colors.indigo,
      Colors.deepPurpleAccent,
    ],
    description: 'Purple tones',
  ),
  'high_contrast': Palette(
    name: 'High Contrast',
    light: ColorScheme.light(
      primary: Colors.yellow,
      secondary: Colors.black,
      surface: Colors.white,
      onSurface: Colors.black,
      primaryContainer: Colors.yellow.shade200,
      secondaryContainer: Colors.grey.shade300,
      error: Colors.red,
      onError: Colors.white,
    ),
    dark: ColorScheme.dark(
      primary: Colors.yellowAccent,
      secondary: Colors.white,
      surface: Colors.black,
      onSurface: Colors.white,
      primaryContainer: Colors.yellow.shade900,
      secondaryContainer: Colors.grey.shade800,
      error: Colors.redAccent,
      onError: Colors.black,
    ),
    accentColors: [
      Colors.yellow,
      Colors.white,
      Colors.black,
      Colors.orange,
      Colors.red,
    ],
    description: 'Black, white, and yellow',
  ),
};
